// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-KUMl5gjHWQq2fdReEq0rlGUWRB0lwbk',
    appId: '1:706688685819:web:6a90904bff98da56e4025e',
    messagingSenderId: '706688685819',
    projectId: 'kultur-yolu-test',
    authDomain: 'kultur-yolu-test.firebaseapp.com',
    storageBucket: 'kultur-yolu-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJgCbV67DWB_EAZu8lG23O92vD4lL5G0Q',
    appId: '1:706688685819:android:f81c2bb115774608e4025e',
    messagingSenderId: '706688685819',
    projectId: 'kultur-yolu-test',
    storageBucket: 'kultur-yolu-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzrFvkomC9mpc0nbjib22I50rIkhlowTE',
    appId: '1:706688685819:ios:c84ac32cda3fe608e4025e',
    messagingSenderId: '706688685819',
    projectId: 'kultur-yolu-test',
    storageBucket: 'kultur-yolu-test.appspot.com',
    iosBundleId: 'com.example.deneme1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzrFvkomC9mpc0nbjib22I50rIkhlowTE',
    appId: '1:706688685819:ios:2a4239ef7c86b57de4025e',
    messagingSenderId: '706688685819',
    projectId: 'kultur-yolu-test',
    storageBucket: 'kultur-yolu-test.appspot.com',
    iosBundleId: 'com.example.deneme1.RunnerTests',
  );
}
